#!/usr/bin/perl
# Simple check of a stateful encoding.
# Usage: check-stateful TOP SRCDIR CHARSET

use warnings;
use strict;

if (@ARGV < 3) {
	print "Usage: check-stateful <top> <srcdir> <charset>\n";
	exit;
}

my $top     = shift @ARGV;
my $srcdir  = shift @ARGV;
my $charset = shift @ARGV;

# charset, modified for use in filenames.
my $charsetf = $charset;
$charsetf =~ s/:/-/g;

command("$top/Iconv -f $charset -t UTF-8 -o $srcdir/tmp-snippet $srcdir/$charsetf-snippet");
command("cmp $srcdir/$charsetf-snippet.UTF-8 $srcdir/tmp-snippet");
command("$top/Iconv -f UTF-8 -t $charset -o $srcdir/tmp-snippet $srcdir/$charsetf-snippet.UTF-8");
command("cmp $srcdir/$charsetf-snippet $srcdir/tmp-snippet");
command("rm -f $srcdir/tmp-snippet");

sub command {
	my $cmd = shift;
	print "> $cmd\n";
	my @output = `$cmd 2>&1`;
	foreach my $line (@output) {
		print "| $line";
	}
	my $status = $? / 256;
	die "$cmd:\nexit status $status\n" if $status;
	return @output;
}

